alter table public.conversations
  add column if not exists assigned_to text,
  add column if not exists bot_paused boolean not null default false,
  add column if not exists bot_paused_at timestamptz,
  add column if not exists last_human_reply_at timestamptz,
  add column if not exists tags jsonb not null default '[]';

alter table public.messages
  add column if not exists metadata jsonb not null default '{}';

do $$
begin
  alter table public.messages drop constraint if exists messages_sender_check;
  alter table public.messages
    add constraint messages_sender_check check (sender in ('patient', 'bot', 'admin', 'human'));
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.citas drop constraint if exists citas_status_check;
  alter table public.citas
    add constraint citas_status_check check (status in ('pending', 'confirmed', 'cancelled', 'failed', 'no_show'));
exception
  when duplicate_object then null;
end $$;

create table if not exists public.processed_whatsapp_messages (
  message_id text primary key,
  from_phone text,
  created_at timestamptz not null default now()
);

create index if not exists processed_whatsapp_messages_created_idx
  on public.processed_whatsapp_messages (created_at);

create index if not exists messages_phone_created_idx
  on public.messages (phone_number, created_at);

create index if not exists messages_created_idx
  on public.messages (created_at desc);

create index if not exists conversations_updated_idx
  on public.conversations (updated_at desc);

create index if not exists conversations_bot_paused_idx
  on public.conversations (bot_paused);

create table if not exists public.conversation_notes (
  id bigint generated by default as identity primary key,
  phone_number text not null references public.conversations(phone_number) on delete cascade,
  body text not null,
  author text not null default 'consultorio',
  created_at timestamptz not null default now()
);

alter table public.conversation_notes
  add column if not exists author text not null default 'consultorio';

create index if not exists conversation_notes_phone_created_idx
  on public.conversation_notes (phone_number, created_at desc);

create table if not exists public.patients (
  phone_number text primary key,
  name text,
  email text,
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  last_patient_message_at timestamptz,
  next_appointment_at timestamptz,
  last_appointment_at timestamptz,
  appointment_count integer not null default 0,
  cancelled_count integer not null default 0,
  failed_count integer not null default 0,
  no_show_count integer not null default 0,
  last_service text,
  last_payment_type text,
  first_visit text,
  status text not null default 'lead' check (status in ('lead', 'active', 'returning', 'human', 'inactive')),
  tags jsonb not null default '[]',
  notes_count integer not null default 0,
  internal_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.patients
  add column if not exists name text,
  add column if not exists email text,
  add column if not exists first_seen_at timestamptz,
  add column if not exists last_seen_at timestamptz,
  add column if not exists last_patient_message_at timestamptz,
  add column if not exists next_appointment_at timestamptz,
  add column if not exists last_appointment_at timestamptz,
  add column if not exists appointment_count integer not null default 0,
  add column if not exists cancelled_count integer not null default 0,
  add column if not exists failed_count integer not null default 0,
  add column if not exists no_show_count integer not null default 0,
  add column if not exists last_service text,
  add column if not exists last_payment_type text,
  add column if not exists first_visit text,
  add column if not exists status text not null default 'lead',
  add column if not exists tags jsonb not null default '[]',
  add column if not exists notes_count integer not null default 0,
  add column if not exists internal_notes text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  alter table public.patients drop constraint if exists patients_status_check;
  alter table public.patients
    add constraint patients_status_check check (status in ('lead', 'active', 'returning', 'human', 'inactive'));
exception
  when duplicate_object then null;
end $$;

create index if not exists patients_updated_idx
  on public.patients (updated_at desc);

create index if not exists patients_next_appointment_idx
  on public.patients (next_appointment_at);

create index if not exists patients_status_idx
  on public.patients (status);

create index if not exists citas_phone_idx on public.citas (phone_number);
create index if not exists citas_slot_start_idx on public.citas (slot_start);
drop index if exists citas_confirmed_slot_start_unique_idx;
create unique index if not exists citas_confirmed_slot_start_with_event_unique_idx
  on public.citas (slot_start)
  where status = 'confirmed' and nullif(google_event_id, '') is not null;

create table if not exists public.knowledge_suggestions (
  id bigint generated by default as identity primary key,
  question text,
  answer text,
  source_phone text,
  conversation_phone text,
  source_message_id bigint,
  intent text,
  variations jsonb not null default '[]',
  category text,
  priority integer not null default 100,
  action text not null default 'answer' check (action in ('answer', 'human_handoff')),
  active boolean not null default true,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'ignored')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

alter table public.knowledge_suggestions
  alter column answer drop not null,
  add column if not exists conversation_phone text,
  add column if not exists intent text,
  add column if not exists variations jsonb not null default '[]',
  add column if not exists category text,
  add column if not exists priority integer not null default 100,
  add column if not exists action text not null default 'answer',
  add column if not exists active boolean not null default true;

do $$
begin
  alter table public.knowledge_suggestions drop constraint if exists knowledge_suggestions_status_check;
  alter table public.knowledge_suggestions
    add constraint knowledge_suggestions_status_check check (status in ('pending', 'approved', 'rejected', 'ignored'));
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.knowledge_suggestions drop constraint if exists knowledge_suggestions_action_check;
  alter table public.knowledge_suggestions
    add constraint knowledge_suggestions_action_check check (action in ('answer', 'human_handoff'));
exception
  when duplicate_object then null;
end $$;

create index if not exists knowledge_suggestions_status_created_idx
  on public.knowledge_suggestions (status, created_at desc);

create index if not exists knowledge_suggestions_active_status_idx
  on public.knowledge_suggestions (active, status, created_at desc);

create or replace function public.cleanup_processed_whatsapp_messages(days_to_keep integer default 30)
returns integer
language plpgsql
as $$
declare
  deleted_count integer;
begin
  delete from public.processed_whatsapp_messages
  where created_at < now() - make_interval(days => days_to_keep);

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

drop view if exists public.appointments;

create view public.appointments as
select
  id,
  phone_number,
  patient_name,
  patient_email,
  google_event_id,
  slot_start,
  slot_end,
  status,
  first_visit,
  payment_type,
  reason,
  created_at
from public.citas;


-- Appointment locks prevent two patients from taking the same slot while Calendar/Supabase confirm.

create table if not exists public.appointment_locks (
  id bigint generated by default as identity primary key,
  slot_start timestamptz not null,
  slot_end timestamptz not null,
  phone_number text,
  lock_token text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create unique index if not exists appointment_locks_slot_unique_idx
  on public.appointment_locks (slot_start, slot_end);

create index if not exists appointment_locks_expires_idx
  on public.appointment_locks (expires_at);

create or replace function public.cleanup_expired_appointment_locks()
returns integer
language plpgsql
as $$
declare
  deleted_count integer;
begin
  delete from public.appointment_locks
  where expires_at < now();

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

create table if not exists public.appointment_reminders (
  id bigint generated by default as identity primary key,
  cita_id bigint references public.citas(id) on delete cascade,
  phone_number text not null,
  reminder_type text not null default 'admin_24h',
  remind_at timestamptz not null,
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed', 'cancelled')),
  payload jsonb not null default '{}',
  sent_at timestamptz,
  error_message text,
  created_at timestamptz not null default now()
);

create unique index if not exists appointment_reminders_cita_type_unique_idx
  on public.appointment_reminders (cita_id, reminder_type);

create index if not exists appointment_reminders_due_idx
  on public.appointment_reminders (status, remind_at);

create table if not exists public.waitlist_entries (
  id bigint generated by default as identity primary key,
  phone_number text not null,
  patient_name text,
  desired_date date,
  desired_range text,
  service text,
  status text not null default 'waiting' check (status in ('waiting', 'notified', 'taken', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists waitlist_entries_date_status_idx
  on public.waitlist_entries (desired_date, status, created_at);

create table if not exists public.daily_reports (
  id bigint generated by default as identity primary key,
  date date not null,
  title text,
  body text not null,
  source text not null default 'manual' check (source in ('manual', 'daily', 'quick_check', 'bulk_cancel')),
  author text,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists daily_reports_created_at_idx
  on public.daily_reports (created_at desc);

create index if not exists daily_reports_date_idx
  on public.daily_reports (date desc);

alter table public.citas add column if not exists error_message text;

do $$
begin
  alter table public.citas drop constraint if exists citas_status_check;
  alter table public.citas
    add constraint citas_status_check check (status in ('pending', 'confirmed', 'cancelled', 'failed', 'expired', 'no_show'));
exception
  when duplicate_object then null;
end $$;

grant usage on schema public to service_role;

grant select, insert, update, delete on table
  public.conversations,
  public.conversation_notes,
  public.patients,
  public.messages,
  public.sessions,
  public.citas,
  public.appointment_locks,
  public.appointment_reminders,
  public.waitlist_entries,
  public.processed_whatsapp_messages,
  public.knowledge_suggestions,
  public.daily_reports
to service_role;

grant select on table public.appointments to service_role;
grant usage, select on all sequences in schema public to service_role;

grant execute on function public.cleanup_processed_whatsapp_messages(integer) to service_role;
grant execute on function public.cleanup_expired_appointment_locks() to service_role;
