alter table public.conversations
  add column if not exists assigned_to text,
  add column if not exists bot_paused boolean not null default false,
  add column if not exists bot_paused_at timestamptz,
  add column if not exists last_human_reply_at timestamptz;

alter table public.messages
  add column if not exists metadata jsonb not null default '{}';

do $$
begin
  alter table public.messages drop constraint if exists messages_sender_check;
  alter table public.messages
    add constraint messages_sender_check check (sender in ('patient', 'bot', 'admin', 'human'));
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.citas drop constraint if exists citas_status_check;
  alter table public.citas
    add constraint citas_status_check check (status in ('pending', 'confirmed', 'cancelled', 'failed', 'no_show'));
exception
  when duplicate_object then null;
end $$;

create table if not exists public.processed_whatsapp_messages (
  message_id text primary key,
  from_phone text,
  created_at timestamptz not null default now()
);

create index if not exists processed_whatsapp_messages_created_idx
  on public.processed_whatsapp_messages (created_at);

create index if not exists messages_phone_created_idx
  on public.messages (phone_number, created_at);

create index if not exists messages_created_idx
  on public.messages (created_at desc);

create index if not exists conversations_updated_idx
  on public.conversations (updated_at desc);

create index if not exists conversations_bot_paused_idx
  on public.conversations (bot_paused);

create index if not exists citas_phone_idx on public.citas (phone_number);
create index if not exists citas_slot_start_idx on public.citas (slot_start);
create unique index if not exists citas_confirmed_slot_start_unique_idx
  on public.citas (slot_start)
  where status = 'confirmed';

create table if not exists public.knowledge_suggestions (
  id bigint generated by default as identity primary key,
  question text,
  answer text not null,
  source_phone text,
  source_message_id bigint,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index if not exists knowledge_suggestions_status_created_idx
  on public.knowledge_suggestions (status, created_at desc);

create or replace function public.cleanup_processed_whatsapp_messages(days_to_keep integer default 30)
returns integer
language plpgsql
as $$
declare
  deleted_count integer;
begin
  delete from public.processed_whatsapp_messages
  where created_at < now() - make_interval(days => days_to_keep);

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

create or replace view public.appointments as
select
  id,
  phone_number,
  patient_name,
  patient_email,
  google_event_id,
  slot_start,
  slot_end,
  status,
  first_visit,
  payment_type,
  reason,
  created_at
from public.citas;
