create table if not exists public.conversations (
  phone_number text primary key,
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  phone_number text not null references public.conversations(phone_number) on delete cascade,
  sender text not null check (sender in ('patient', 'bot')),
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_phone_created_idx
  on public.messages (phone_number, created_at);

create index if not exists conversations_updated_idx
  on public.conversations (updated_at desc);
