create table if not exists public.conversations (
  phone_number text primary key,
  assigned_to text,
  bot_paused boolean not null default false,
  bot_paused_at timestamptz,
  last_human_reply_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.conversations
  add column if not exists assigned_to text,
  add column if not exists bot_paused boolean not null default false,
  add column if not exists bot_paused_at timestamptz,
  add column if not exists last_human_reply_at timestamptz;

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  phone_number text not null references public.conversations(phone_number) on delete cascade,
  sender text not null,
  body text not null,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

alter table public.messages
  add column if not exists metadata jsonb not null default '{}';

do $$
begin
  alter table public.messages drop constraint if exists messages_sender_check;
  alter table public.messages
    add constraint messages_sender_check check (sender in ('patient', 'bot', 'admin', 'human'));
exception
  when duplicate_object then null;
end $$;

create index if not exists messages_phone_created_idx
  on public.messages (phone_number, created_at);

create index if not exists messages_created_idx
  on public.messages (created_at desc);

create index if not exists conversations_updated_idx
  on public.conversations (updated_at desc);

create index if not exists conversations_bot_paused_idx
  on public.conversations (bot_paused);

create table if not exists public.sessions (
  phone_number text primary key,
  step text not null default 'collecting',
  data jsonb not null default '{}',
  updated_at timestamptz not null default now()
);

create table if not exists public.citas (
  id bigint generated by default as identity primary key,
  phone_number text not null,
  patient_name text,
  patient_email text,
  google_event_id text,
  slot_start timestamptz not null,
  slot_end timestamptz not null,
  status text not null default 'confirmed' check (status in ('pending', 'confirmed', 'cancelled', 'failed', 'expired', 'no_show')),
  error_message text,
  first_visit text,
  payment_type text,
  reason text,
  created_at timestamptz not null default now()
);

do $$
begin
  alter table public.citas drop constraint if exists citas_status_check;
  alter table public.citas
    add constraint citas_status_check check (status in ('pending', 'confirmed', 'cancelled', 'failed', 'expired', 'no_show'));
exception
  when duplicate_object then null;
end $$;

create index if not exists citas_phone_idx on public.citas (phone_number);
create index if not exists citas_slot_start_idx on public.citas (slot_start);
create unique index if not exists citas_confirmed_slot_start_unique_idx
  on public.citas (slot_start)
  where status = 'confirmed';


create table if not exists public.appointment_locks (
  id bigint generated by default as identity primary key,
  slot_start timestamptz not null,
  slot_end timestamptz not null,
  phone_number text,
  lock_token text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create unique index if not exists appointment_locks_slot_unique_idx
  on public.appointment_locks (slot_start, slot_end);

create index if not exists appointment_locks_expires_idx
  on public.appointment_locks (expires_at);

create or replace function public.cleanup_expired_appointment_locks()
returns integer
language plpgsql
as $$
declare
  deleted_count integer;
begin
  delete from public.appointment_locks
  where expires_at < now();

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

create table if not exists public.appointment_reminders (
  id bigint generated by default as identity primary key,
  cita_id bigint references public.citas(id) on delete cascade,
  phone_number text not null,
  reminder_type text not null default 'admin_24h',
  remind_at timestamptz not null,
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed', 'cancelled')),
  payload jsonb not null default '{}',
  sent_at timestamptz,
  error_message text,
  created_at timestamptz not null default now()
);

create unique index if not exists appointment_reminders_cita_type_unique_idx
  on public.appointment_reminders (cita_id, reminder_type);

create index if not exists appointment_reminders_due_idx
  on public.appointment_reminders (status, remind_at);

create table if not exists public.processed_whatsapp_messages (
  message_id text primary key,
  from_phone text,
  created_at timestamptz not null default now()
);

create index if not exists processed_whatsapp_messages_created_idx
  on public.processed_whatsapp_messages (created_at);

create or replace function public.cleanup_processed_whatsapp_messages(days_to_keep integer default 30)
returns integer
language plpgsql
as $$
declare
  deleted_count integer;
begin
  delete from public.processed_whatsapp_messages
  where created_at < now() - make_interval(days => days_to_keep);

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

create table if not exists public.knowledge_suggestions (
  id bigint generated by default as identity primary key,
  question text,
  answer text,
  source_phone text,
  conversation_phone text,
  source_message_id bigint,
  category text,
  action text not null default 'answer' check (action in ('answer', 'human_handoff')),
  active boolean not null default true,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'ignored')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

alter table public.knowledge_suggestions
  alter column answer drop not null,
  add column if not exists conversation_phone text,
  add column if not exists category text,
  add column if not exists action text not null default 'answer',
  add column if not exists active boolean not null default true;

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'knowledge_suggestions_status_check'
      and conrelid = 'public.knowledge_suggestions'::regclass
  ) then
    alter table public.knowledge_suggestions drop constraint knowledge_suggestions_status_check;
  end if;
end $$;

alter table public.knowledge_suggestions
  add constraint knowledge_suggestions_status_check check (status in ('pending', 'approved', 'rejected', 'ignored'));

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'knowledge_suggestions_action_check'
      and conrelid = 'public.knowledge_suggestions'::regclass
  ) then
    alter table public.knowledge_suggestions drop constraint knowledge_suggestions_action_check;
  end if;
end $$;

alter table public.knowledge_suggestions
  add constraint knowledge_suggestions_action_check check (action in ('answer', 'human_handoff'));

create index if not exists knowledge_suggestions_status_created_idx
  on public.knowledge_suggestions (status, created_at desc);

create index if not exists knowledge_suggestions_active_status_idx
  on public.knowledge_suggestions (active, status, created_at desc);

create or replace view public.appointments as
select
  id,
  phone_number,
  patient_name,
  patient_email,
  google_event_id,
  slot_start,
  slot_end,
  status,
  first_visit,
  payment_type,
  reason,
  error_message,
  created_at
from public.citas;

grant usage on schema public to service_role;

grant select, insert, update, delete on table
  public.conversations,
  public.messages,
  public.sessions,
  public.citas,
  public.appointment_locks,
  public.appointment_reminders,
  public.processed_whatsapp_messages,
  public.knowledge_suggestions
to service_role;

grant select on table public.appointments to service_role;
grant usage, select on all sequences in schema public to service_role;

grant execute on function public.cleanup_processed_whatsapp_messages(integer) to service_role;
grant execute on function public.cleanup_expired_appointment_locks() to service_role;
