create table if not exists public.conversations (
  phone_number text primary key,
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  phone_number text not null references public.conversations(phone_number) on delete cascade,
  sender text not null check (sender in ('patient', 'bot')),
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_phone_created_idx
  on public.messages (phone_number, created_at);

create index if not exists conversations_updated_idx
  on public.conversations (updated_at desc);

create table if not exists public.sessions (
  phone_number text primary key,
  step text not null default 'collecting',
  data jsonb not null default '{}',
  updated_at timestamptz not null default now()
);

create table if not exists public.citas (
  id bigint generated by default as identity primary key,
  phone_number text not null,
  patient_name text,
  patient_email text,
  google_event_id text,
  slot_start timestamptz not null,
  slot_end timestamptz not null,
  status text not null default 'confirmed' check (status in ('confirmed', 'cancelled', 'no_show')),
  first_visit text,
  payment_type text,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists citas_phone_idx on public.citas (phone_number);
create index if not exists citas_slot_start_idx on public.citas (slot_start);
